-- ---------------------------------------------------------------------------
-- 0036_the_throw.sql -- LUMEA'S FIFTEEN SECONDS
--
-- Generated by _to_delete/build0036.py. Do not hand-edit; edit the builder.
--
-- The only genuinely new INTERACTION in the whole rework, and the reason it
-- was left until last: an enemy walks into Lumea's tornado, and Lumea's
-- controller gets fifteen seconds to choose where to throw them WHILE
-- EVERYTHING ELSE WAITS. That is a pending decision on the match, belonging to
-- the side whose turn it is not, with its own clock and its own default -- a
-- shape this engine has never had.
--
-- THE CLOCK. A pending decision does not get a second deadline column. While
-- one is open, `turn_deadline` IS the decision's deadline, and what the turn
-- had left is parked in `pending.resumeMs` and given back when the decision
-- closes. One clock means one realtime push, one countdown on the client, and
-- one thing for force_timeout to look at -- which is what "everything else
-- waits" has to mean if it is to mean anything.
--
-- WHAT IS BLOCKED. Everything. The guard goes in cn_begin_act, which is the
-- chokepoint every move, strike, ability and guard already passes through, and
-- separately in submit_wait and end_turn, which are the two that do not.
--
-- THE DEFAULT. Nothing. Fifteen seconds pass and the gale dies down with the
-- unit where it stood. A default that MOVED somebody would make running the
-- clock out a move in itself, and a decision you can lose by not making is not
-- a decision, it is a penalty.
--
-- AND A REFACTOR THAT EARNS ITS PLACE. 0035 made cn_move the first place in
-- the game where a unit could die, and inlined the trap, the crown check and
-- the settling to do it. The throw is the second such place, so all three come
-- out into cn_spring, cn_win_after_death and cn_finish, and cn_move is
-- re-spliced to call them. Two copies of "who won" is how a ranked ladder
-- quietly stops agreeing with itself.
-- ---------------------------------------------------------------------------

begin;

-- ---------------------------------------------------------------------------
-- 1. the vocabulary of a pending decision
-- ---------------------------------------------------------------------------
/** The open decision, or null. The ONLY reader of the key's name. */
create or replace function public.cn_pending(p_st jsonb)
returns jsonb language sql immutable as $$
  select case when p_st->'pending' = 'null'::jsonb then null else p_st->'pending' end
$$;

/** How long Lumea's controller gets. The card says fifteen seconds. */
create or replace function public.cn_throw_secs() returns int
language sql immutable as $$ select 15 $$;

/** How far a gale carries. Not on the card, so it is here rather than on the
 *  row: it is a fact about tornadoes and there is one tornado. */
create or replace function public.cn_throw_reach() returns int
language sql immutable as $$ select 3 $$;

revoke execute on function public.cn_pending(jsonb)   from public, anon, authenticated;
revoke execute on function public.cn_throw_secs()     from public, anon, authenticated;
revoke execute on function public.cn_throw_reach()    from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 2. three things that were inlined in 0035 and are now needed twice
-- ---------------------------------------------------------------------------
/** The trap lying on a tile, or null. A tornado is not one and a wall is not
 *  one; only a bomb goes off under a boot. */
create or replace function public.cn_trap_at(p_st jsonb, p_x int, p_y int)
returns jsonb language sql stable as $$
  select e from jsonb_array_elements(coalesce(p_st->'obstacles', '[]'::jsonb)) e
   where cn_obj_kind(e) = 'bomb'
     and (e->>'x')::int = p_x and (e->>'y')::int = p_y
   limit 1
$$;

/**
 * Set off whatever this unit is now standing on, and return the new state.
 *
 * Called AFTER the unit has been placed, by both of the two ways a unit can
 * arrive somewhere it did not choose to be. The unit leaves the list if the
 * trap finishes it -- the same rule poison follows in advance_turn -- so the
 * caller asks "is it still there" rather than being handed a flag.
 *
 * The damage is read off the OBJECT and not looked up from whoever planted it:
 * Mako can be long dead by the time somebody treads on this.
 */
create or replace function public.cn_spring(p_st jsonb, p_unit text)
returns jsonb language plpgsql as $$
declare
  v_me jsonb; v_trap jsonb; v_hurt int; v_dead boolean;
  u jsonb; e jsonb; v_out jsonb := '[]'::jsonb; v_rocks jsonb := '[]'::jsonb;
begin
  for u in select * from jsonb_array_elements(p_st->'units') loop
    if u->>'id' = p_unit then v_me := u; end if;
  end loop;
  if v_me is null then return p_st; end if;

  v_trap := cn_trap_at(p_st, (v_me->>'x')::int, (v_me->>'y')::int);
  if v_trap is null then return p_st; end if;

  v_hurt := coalesce((v_trap->>'dmg')::int, 0);
  v_dead := (v_me->>'hp')::int - v_hurt <= 0;

  for u in select * from jsonb_array_elements(p_st->'units') loop
    if u->>'id' = p_unit then
      u := jsonb_set(u, '{hp}', to_jsonb((u->>'hp')::int - v_hurt));
      if v_dead then continue; end if;
    end if;
    v_out := v_out || u;
  end loop;
  for e in select * from jsonb_array_elements(coalesce(p_st->'obstacles', '[]'::jsonb)) loop
    if e->>'id' <> v_trap->>'id' then v_rocks := v_rocks || e; end if;
  end loop;

  p_st := jsonb_set(p_st, '{units}', v_out);
  p_st := jsonb_set(p_st, '{obstacles}', v_rocks);
  p_st := state_log(p_st, (v_me->>'name') || ' steps on a trap for ' || v_hurt
    || case when v_dead then ' -- destroyed.' else '.' end);
  -- The board animates from `fx`, and a trap is one blow from nobody to
  -- somebody. `atk` is null rather than the summoner: the summoner did not
  -- act this turn and may not be alive.
  p_st := jsonb_set(p_st, '{fx}', jsonb_build_object(
    'seq', coalesce((p_st->'fx'->>'seq')::int, 0) + 1,
    'kind', 'ability', 'why', 'trap', 'atk', null, 'tgt', p_unit,
    'hits', jsonb_build_array(jsonb_build_object('id', p_unit, 'dmg', v_hurt)),
    'swings', '[]'::jsonb,
    'dmg', v_hurt, 'heal', 0, 'counter', 0, 'burnAtk', 0, 'burnTgt', 0,
    'killedTgt', v_dead, 'killedAtk', false, 'newBurn', false,
    'cured', false, 'parry', false, 'tree', false), true);
  return p_st;
end $$;

/**
 * Who has won, given that this unit has just fallen -- or null if nobody has.
 *
 * A crown takes the kingdom with it, and so does the last body. Both were
 * written out inside cn_attack and again inside cn_move; this is the one
 * copy, and the throw is what made a third copy imminent.
 */
create or replace function public.cn_win_after_death(p_st jsonb, p_dead jsonb)
returns text language sql stable as $$
  select case
    when coalesce((p_dead->>'royal')::boolean, false)
      then case when p_dead->>'owner' = 'host' then 'guest' else 'host' end
    when not exists (select 1 from jsonb_array_elements(p_st->'units') q
                      where q->>'owner' = p_dead->>'owner')
      then case when p_dead->>'owner' = 'host' then 'guest' else 'host' end
  end
$$;

/** End the match the way cn_attack ends it, from anywhere. A match that
 *  finishes on a trap has to settle exactly as one that finishes on a blow,
 *  or a ranked ladder quietly stops agreeing with itself. */
create or replace function public.cn_finish(m public.matches, p_st jsonb, p_win text)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare v public.matches;
begin
  if m.ranked then perform finish_match(m.id, p_win, 'defeat'); end if;
  p_st := jsonb_set(p_st, '{winner}', to_jsonb(p_win));
  p_st := state_log(p_st,
    case when p_win = 'host' then m.host_name else m.guest_name end || ' wins.');
  update public.matches
     set state = p_st, status = 'finished', winner = p_win,
         turn_deadline = null, updated_at = now()
   where id = m.id returning * into v;
  return v;
end $$;

revoke execute on function public.cn_trap_at(jsonb, int, int)        from public, anon, authenticated;
revoke execute on function public.cn_spring(jsonb, text)             from public, anon, authenticated;
revoke execute on function public.cn_win_after_death(jsonb, jsonb)   from public, anon, authenticated;
revoke execute on function public.cn_finish(public.matches, jsonb, text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------
-- 3. nobody acts while a decision is open
-- ---------------------------------------------------------------------------
-- cn_begin_act is the chokepoint every move, strike, ability and guard passes
-- through, which is why the guard is here rather than in five shells.
create or replace function public.cn_begin_act(p_st jsonb, p_side text, p_unit text)
returns jsonb language plpgsql as $$
declare
  v_active text; v_acts int; v_cap int; u jsonb; v_me jsonb;
  v_out jsonb := '[]'::jsonb;
begin
  -- Nobody acts while a decision is open. Fifteen seconds is short enough
  -- that waiting is bearable and long enough that it has to be enforced
  -- rather than hoped for.
  if cn_pending(p_st) is not null then
    raise exception 'a throw is pending';
  end if;
  for u in select * from jsonb_array_elements(p_st->'units') loop
    if u->>'id' = p_unit then v_me := u; end if;
  end loop;
  if v_me is null then raise exception 'no such unit'; end if;
  if v_me->>'owner' <> p_side then raise exception 'that is not your unit'; end if;
  if coalesce((v_me->>'spent')::boolean, false) then
    raise exception 'that unit has already had its go this turn';
  end if;

  v_active := nullif(p_st->>'active', '');
  v_acts   := coalesce((p_st->>'acts')::int, 0);
  v_cap    := cn_acts_cap(p_st);

  -- Already the active unit: it moved a moment ago and is now striking. Same
  -- go, nothing more to charge.
  if v_active is not distinct from p_unit then return p_st; end if;

  if v_acts >= v_cap then raise exception 'no actions left this turn'; end if;

  -- Turning to a different unit ends whatever the last one was in the middle
  -- of. It moved and chose not to strike; that was its go.
  if v_active is not null then
    for u in select * from jsonb_array_elements(p_st->'units') loop
      if u->>'id' = v_active then u := jsonb_set(u, '{spent}', 'true'::jsonb); end if;
      v_out := v_out || u;
    end loop;
    p_st := jsonb_set(p_st, '{units}', v_out);
  end if;

  p_st := jsonb_set(p_st, '{acts}', to_jsonb(v_acts + 1));
  p_st := jsonb_set(p_st, '{active}', to_jsonb(p_unit));
  return p_st;
end $$;
create or replace function public.submit_wait(p_match uuid)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare m public.matches; v_side text; v_active text; v_st jsonb;
begin
  select * into m from public.matches where id = p_match for update;
  if m.id is null then raise exception 'no such match'; end if;
  if m.status <> 'active' then raise exception 'match is not running'; end if;
  v_side := side_of(m, auth.uid());
  if v_side is null then raise exception 'you are spectating this match'; end if;
  if m.state->>'turn' <> v_side then raise exception 'not your turn'; end if;

  v_st := m.state;
  -- submit_wait and end_turn are the two that never reach cn_begin_act.
  if cn_pending(v_st) is not null then raise exception 'a throw is pending'; end if;
  v_active := nullif(v_st->>'active', '');
  if v_active is null then return m; end if;   -- nobody mid-go; nothing to end

  v_st := cn_end_act(v_st, v_active);
  update public.matches set state = v_st, updated_at = now()
   where id = m.id returning * into m;
  return m;
end $$;
create or replace function public.end_turn(p_match uuid)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare
  m public.matches; side text;
begin
  select * into m from public.matches where id = p_match;
  if m.id is null then raise exception 'no such match'; end if;
  if m.status <> 'active' then raise exception 'match is not running'; end if;
  side := side_of(m, auth.uid());
  if side is null then raise exception 'you are spectating this match'; end if;
  if m.state->>'turn' <> side then raise exception 'not your turn'; end if;
  if cn_pending(m.state) is not null then raise exception 'a throw is pending'; end if;
  return advance_turn(p_match, null);
end $$;

-- ---------------------------------------------------------------------------
-- 4. the walk, re-spliced onto the helpers -- and the gale
-- ---------------------------------------------------------------------------
create or replace function public.cn_move(p_match uuid, p_side text, p_unit text, p_x integer, p_y integer)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare
  m public.matches; v_st jsonb; u jsonb; e jsonb; v_me jsonb;
  v_out jsonb := '[]'::jsonb; v_rocks jsonb := '[]'::jsonb;
  v_reach text[]; v_felled boolean := false;
  v_win text; v_gale jsonb; v_left int;
begin
  select * into m from public.matches where id = p_match for update;
  v_st := m.state;
  for u in select * from jsonb_array_elements(v_st->'units') loop
    if u->>'id' = p_unit then v_me := u; end if;
  end loop;
  if v_me is null then raise exception 'no such unit'; end if;
  if v_me->>'owner' <> p_side then raise exception 'that is not your unit'; end if;
  if (v_me->>'moved')::boolean then raise exception 'that unit already moved'; end if;

  -- Opens an activation, or continues the one this unit is already in.
  -- Moving deliberately does NOT close it: the unit may still strike, and
  -- move-then-strike is one action, not two. cn_begin_act is what charges
  -- the turn's budget, and it raises if there is nothing left to spend.
  v_st := cn_begin_act(v_st, p_side, p_unit);

  v_reach := cn_reach(v_st, v_me);
  if not ((p_x || ',' || p_y) = any(v_reach)) then
    raise exception 'that unit cannot reach that tile';
  end if;

  -- WHAT IS ON THE TILE. Anything solid was already excluded by cn_reach --
  -- you cannot walk into a tree unless you trample, and you cannot walk into
  -- a wall at all -- so what is standing here is a trap, a tornado, or a tree
  -- under a trampler. The trap is NOT handled here any more: the unit is put
  -- down first and cn_spring is asked what it landed on, because the throw
  -- needs the same answer and two copies of it would drift.
  for e in select * from jsonb_array_elements(coalesce(v_st->'obstacles', '[]'::jsonb)) loop
    if (e->>'x')::int = p_x and (e->>'y')::int = p_y
       and cn_obj_kind(e) = 'tree' then
      v_felled := true;                        -- trampled, and gone
    else
      if (e->>'x')::int = p_x and (e->>'y')::int = p_y
         and cn_obj_kind(e) = 'tornado'
         and e->>'owner' is not null and e->>'owner' <> p_side then
        -- Only an ENEMY tornado takes hold. Walking your own unit into your
        -- own gale to be thrown somewhere useful would make Lumea a taxi.
        v_gale := e;
      end if;
      v_rocks := v_rocks || e;                 -- a trap and a tornado both stay
    end if;
  end loop;

  for u in select * from jsonb_array_elements(v_st->'units') loop
    if u->>'id' = p_unit then
      u := jsonb_set(jsonb_set(u, '{x}', to_jsonb(p_x)), '{y}', to_jsonb(p_y));
      u := jsonb_set(u, '{moved}', 'true'::jsonb);
    end if;
    v_out := v_out || u;
  end loop;

  v_st := jsonb_set(v_st, '{units}', v_out);
  v_st := jsonb_set(v_st, '{obstacles}', v_rocks);
  v_st := state_log(v_st, (v_me->>'name') || ' advances.');
  if v_felled then
    v_st := state_log(v_st, (v_me->>'name') || ' walks through a tree. It comes down.');
  end if;
  -- The trap, the falling and the ending, all three through the helpers that
  -- 0036 pulled out of here -- because the throw does exactly the same three
  -- things and two copies of "who won" is how a ranked ladder quietly stops
  -- agreeing with itself.
  v_st := cn_spring(v_st, p_unit);
  if not exists (select 1 from jsonb_array_elements(v_st->'units') q
                  where q->>'id' = p_unit) then
    if coalesce((v_me->>'royal')::boolean, false) then
      v_st := state_log(v_st, 'The crown has fallen.');
    end if;
    v_win := cn_win_after_death(v_st, v_me);
    v_gale := null;          -- a unit the trap finished is not thrown anywhere
  end if;

  if v_win is not null then return cn_finish(m, v_st, v_win); end if;

  -- LUMEA'S FIFTEEN SECONDS. The gale has hold of somebody, so everything
  -- stops and the clock changes hands: what the turn had left is parked, and
  -- turn_deadline becomes the decision's deadline instead. One clock, one
  -- realtime push, one countdown -- see this file's header.
  if v_gale is not null then
    v_left := greatest(0, round(extract(epoch from
                (coalesce(m.turn_deadline, now()) - now())) * 1000))::int;
    v_st := jsonb_set(v_st, '{pending}', jsonb_build_object(
      'kind', 'throw', 'side', v_gale->>'owner', 'unit', p_unit,
      'obj', v_gale->>'id', 'resumeMs', v_left), true);
    v_st := state_log(v_st, (v_me->>'name') || ' is caught in the gale.');
    update public.matches
       set state = v_st,
           turn_deadline = now() + (cn_throw_secs() || ' seconds')::interval,
           updated_at = now()
     where id = m.id returning * into m;
    return m;
  end if;

  update public.matches set state = v_st, updated_at = now()
   where id = m.id returning * into m;
  return m;
end
$$;

-- ---------------------------------------------------------------------------
-- 5. the decision itself
-- ---------------------------------------------------------------------------
/**
 * Throw the unit the gale has hold of, or let it go.
 *
 * p_target is a tile ('@x,y', 0035's wire format) or NULL, which means "leave
 * them" and is also what the clock running out does. Called by the side whose
 * turn it is NOT, which is the whole novelty: every other rule in this engine
 * asks "is it your turn", and this one asks "is it your decision".
 */
create or replace function public.cn_throw(p_match uuid, p_side text, p_target text)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare
  m public.matches; v_st jsonb; v_p jsonb; u jsonb; e jsonb;
  v_me jsonb; v_tile int[]; v_dist int; v_out jsonb := '[]'::jsonb;
  v_win text; v_resume int;
begin
  select * into m from public.matches where id = p_match for update;
  if m.id is null then raise exception 'no such match'; end if;
  if m.status <> 'active' then raise exception 'match is not running'; end if;
  v_st := m.state;

  v_p := cn_pending(v_st);
  if v_p is null then raise exception 'nothing is pending'; end if;
  if v_p->>'kind' <> 'throw' then raise exception 'that is not a throw'; end if;
  if v_p->>'side' <> p_side then raise exception 'that is not your decision'; end if;

  for u in select * from jsonb_array_elements(v_st->'units') loop
    if u->>'id' = v_p->>'unit' then v_me := u; end if;
  end loop;

  -- The gale can only be holding somebody who is still standing there, but a
  -- decision is fifteen seconds long and nothing else in this engine assumes
  -- a unit is where it was fifteen seconds ago. If it has gone, the decision
  -- simply closes.
  if v_me is not null and p_target is not null then
    v_tile := cn_tile_target(p_target);
    if v_tile is null then raise exception 'that ability needs a tile'; end if;
    if v_tile[1] < 0 or v_tile[2] < 0
       or v_tile[1] >= (v_st->'board'->>'w')::int
       or v_tile[2] >= (v_st->'board'->>'h')::int then
      raise exception 'that tile is not on the board';
    end if;
    v_dist := cn_cheb((v_me->>'x')::int, (v_me->>'y')::int, v_tile[1], v_tile[2]);
    if v_dist < 1 or v_dist > cn_throw_reach() then
      raise exception 'out of range';
    end if;
    -- No line of sight: a gale throws OVER things. What it cannot do is put
    -- somebody inside a wall or on top of another unit -- and a trap is
    -- neither, which is the point of the spring below.
    for u in select * from jsonb_array_elements(v_st->'units') loop
      if (u->>'x')::int = v_tile[1] and (u->>'y')::int = v_tile[2] then
        raise exception 'that tile is taken';
      end if;
    end loop;
    for e in select * from jsonb_array_elements(coalesce(v_st->'obstacles', '[]'::jsonb)) loop
      if (e->>'x')::int = v_tile[1] and (e->>'y')::int = v_tile[2]
         and cn_obj_solid(cn_obj_kind(e)) then
        raise exception 'that tile is taken';
      end if;
    end loop;

    for u in select * from jsonb_array_elements(v_st->'units') loop
      if u->>'id' = v_me->>'id' then
        u := jsonb_set(jsonb_set(u, '{x}', to_jsonb(v_tile[1])),
                       '{y}', to_jsonb(v_tile[2]));
      end if;
      v_out := v_out || u;
    end loop;
    v_st := jsonb_set(v_st, '{units}', v_out);
    v_st := state_log(v_st, (v_me->>'name') || ' is hurled across the field.');
    v_st := jsonb_set(v_st, '{fx}', jsonb_build_object(
      'seq', coalesce((v_st->'fx'->>'seq')::int, 0) + 1,
      'kind', 'ability', 'why', 'throw', 'atk', null, 'tgt', v_me->>'id',
      'hits', '[]'::jsonb, 'swings', '[]'::jsonb,
      'dmg', 0, 'heal', 0, 'counter', 0, 'burnAtk', 0, 'burnTgt', 0,
      'killedTgt', false, 'killedAtk', false, 'newBurn', false,
      'cured', false, 'parry', false, 'tree', false), true);

    -- And you can be thrown onto a trap, which is the best thing in the game.
    v_st := cn_spring(v_st, v_me->>'id');
    if not exists (select 1 from jsonb_array_elements(v_st->'units') q
                    where q->>'id' = v_me->>'id') then
      if coalesce((v_me->>'royal')::boolean, false) then
        v_st := state_log(v_st, 'The crown has fallen.');
      end if;
      v_win := cn_win_after_death(v_st, v_me);
    end if;
  else
    v_st := state_log(v_st, 'The gale dies down.');
  end if;

  -- The decision closes either way, and the turn gets its clock back with
  -- what it had left on it. Parked rather than restored as an absolute time,
  -- because fifteen seconds of somebody else's thinking must not come out of
  -- the mover's turn.
  v_resume := coalesce((v_p->>'resumeMs')::int, 0);
  v_st := v_st - 'pending';

  if v_win is not null then return cn_finish(m, v_st, v_win); end if;

  update public.matches
     set state = v_st,
         turn_deadline = now() + (v_resume || ' milliseconds')::interval,
         updated_at = now()
   where id = m.id returning * into m;
  return m;
end $$;

/** The authorisation shell. Note what it does NOT check: whose turn it is. */
create or replace function public.submit_throw(p_match uuid, p_target text)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare m public.matches; v_side text;
begin
  select * into m from public.matches where id = p_match;
  if m.id is null then raise exception 'no such match'; end if;
  v_side := side_of(m, auth.uid());
  if v_side is null then raise exception 'you are spectating this match'; end if;
  -- Two seconds of slack, the same as every other deadline in this engine:
  -- a decision made on the fifteenth second should not be lost to the round
  -- trip that carries it.
  if now() > m.turn_deadline + interval '2 seconds' then
    raise exception 'your time ran out';
  end if;
  return cn_throw(p_match, v_side, p_target);
end $$;

revoke execute on function public.cn_throw(uuid, text, text) from public, anon, authenticated;
grant execute on function public.submit_throw(uuid, text) to authenticated;

-- ---------------------------------------------------------------------------
-- 6. and what happens when nobody decides
-- ---------------------------------------------------------------------------
create or replace function public.force_timeout(p_match uuid)
returns public.matches
language plpgsql security definer set search_path = public as $$
declare m public.matches; v_loser text;
begin
  select * into m from public.matches where id = p_match;
  if m.id is null then raise exception 'no such match'; end if;
  if m.turn_deadline is null then return m; end if;
  if now() <= m.turn_deadline + interval '2 seconds' then return m; end if;

  if m.status = 'deploying' then return cn_set_ready(p_match, null, true); end if;
  if m.status <> 'active' then return m; end if;

  -- A pending decision owns the clock while it is open, so an expired clock
  -- here is the DECISION expiring and not the turn. The default is nothing --
  -- see this file's header on why a default that moved somebody would make
  -- running the clock out a move in itself.
  if cn_pending(m.state) is not null then
    return cn_throw(p_match, cn_pending(m.state)->>'side', null);
  end if;

  v_loser := case when m.state->>'turn' = 'host' then m.host_name else m.guest_name end;
  return advance_turn(p_match, v_loser || ' ran out of time.', true);
end $$;

-- ---------------------------------------------------------------------------
-- 7. what this migration claims to have done
-- ---------------------------------------------------------------------------
do $$
declare r record;
begin
  select
    cn_throw_secs() = 15                                          as fifteen,
    cn_throw_reach() = 3                                          as reach,
    cn_pending('{}'::jsonb) is null                               as no_pending_is_null,
    cn_pending('{"pending": null}'::jsonb) is null                as json_null_too,
    cn_pending('{"pending": {"kind": "throw"}}'::jsonb) is not null as one_is_seen,
    has_function_privilege('authenticated', 'public.submit_throw(uuid, text)', 'execute')
                                                                  as players_may_throw,
    not has_function_privilege('authenticated', 'public.cn_throw(uuid, text, text)', 'execute')
                                                                  as engine_is_shut
  into r;
  raise notice '0036: fifteen=% reach=% no_pending_is_null=% json_null_too=% one_is_seen=% players_may_throw=% engine_is_shut=%',
    r.fifteen, r.reach, r.no_pending_is_null, r.json_null_too, r.one_is_seen,
    r.players_may_throw, r.engine_is_shut;
end $$;

commit;
