-- 0115: the descriptive dashboards (card performance, tier list, synergy,
-- best teams) must never be built from "teach" games by default.
--
-- Jared, testing the new Training tab: "why don't I just take the displayed
-- data from the 'teach' button? I don't see the point in 'train' then."
--
-- Good catch -- and it exposed a real gap. A "teach" run's games are half
-- played by the CURRENT live brain and half by a freshly mutated candidate
-- that might lose and get thrown away. 0114 shipped the four dashboard
-- functions filtering only by an explicit p_run id -- when p_run was left
-- null ("all-time data"), they pooled every sim_unit_stats row regardless
-- of which training_runs.kind produced it. That means a user who only ever
-- ran Teach would see card/tier/synergy numbers partly generated by a
-- rejected, unpromoted brain -- exactly the kind of not-legit data this
-- whole feature was built to avoid.
--
-- The fix: when p_run is null, restrict to games from 'train'-kind runs
-- only (admin_spot_check_team already inserts its own kind='train' run, so
-- spot-checks keep counting). When p_run IS given explicitly (the
-- "Latest run only" scope), the caller gets exactly that run's data,
-- whatever kind it is -- AdminTraining.tsx is changed in the same change to
-- stop offering that scope right after a Teach run, since a single mixed
-- run is not a clean read either; it still works from the RPC side for an
-- admin who deliberately wants to inspect one run's raw numbers.
create or replace function public.admin_card_performance(p_run uuid default null)
returns table (
  card_slug text, role text, royal boolean, games int, win_rate numeric,
  avg_turns_alive numeric, avg_damage_dealt numeric, avg_damage_taken numeric,
  avg_healing_done numeric, avg_kills numeric, carried_count int, carry_rate numeric
)
language sql
stable
as $$
  select s.card_slug, max(s.role), bool_or(s.royal),
    count(*)::int, avg(s.won::int)::numeric,
    avg(s.turns_alive)::numeric, avg(s.damage_dealt)::numeric, avg(s.damage_taken)::numeric,
    avg(s.healing_done)::numeric, avg(s.kills)::numeric,
    sum(s.carried::int)::int, avg(s.carried::int)::numeric
  from public.sim_unit_stats s
  join public.training_runs r on r.id = s.training_run_id
  where (p_run is not null and s.training_run_id = p_run)
     or (p_run is null and r.kind = 'train')
  group by s.card_slug
  order by 5 desc
$$;

create or replace function public.admin_pair_synergy(p_run uuid default null, p_min_games int default 15)
returns table (card_a text, card_b text, games int, win_rate numeric, lift numeric)
language sql
stable
as $$
  with pairs as (
    select s1.sim_game_id, s1.card_slug as card_a, s2.card_slug as card_b, s1.won
    from public.sim_unit_stats s1
    join public.sim_unit_stats s2
      on s1.sim_game_id = s2.sim_game_id and s1.side = s2.side and s1.card_slug < s2.card_slug
    join public.training_runs r on r.id = s1.training_run_id
    where ((p_run is not null and s1.training_run_id = p_run)
        or (p_run is null and r.kind = 'train'))
      and s2.training_run_id = s1.training_run_id
  ),
  agg as (
    select card_a, card_b, count(*)::int as games, avg(won::int)::numeric as win_rate
    from pairs group by card_a, card_b
  ),
  solo as (
    select s.card_slug, avg(s.won::int)::numeric as win_rate
    from public.sim_unit_stats s
    join public.training_runs r on r.id = s.training_run_id
    where (p_run is not null and s.training_run_id = p_run)
       or (p_run is null and r.kind = 'train')
    group by s.card_slug
  )
  select a.card_a, a.card_b, a.games, a.win_rate,
    (a.win_rate - (sa.win_rate + sb.win_rate) / 2.0) as lift
  from agg a
  join solo sa on sa.card_slug = a.card_a
  join solo sb on sb.card_slug = a.card_b
  where a.games >= p_min_games
  order by lift desc
$$;
-- admin_tier_list and admin_best_teams both call the two functions above
-- rather than querying sim_unit_stats directly, so this fix reaches all
-- four dashboards without touching either of them.

-- Self-test: a card that ONLY appears in a teach-kind run's stats must not
-- show up in admin_card_performance(null) ("all-time"), and must still show
-- up when that run's id is passed explicitly (an admin deliberately
-- inspecting one run's raw numbers still gets the truth).
do $$
declare
  v_teach_run uuid; v_train_run uuid; v_base uuid; v_cand uuid; v_sim_game uuid;
  v_found boolean;
begin
  select id into v_base from public.bot_brains where level = 3 and is_live limit 1;
  insert into public.bot_brains (label, level, weights, created_by)
    values ('ZZ 0115 self-test candidate', 3, (select weights from public.bot_brains where id = v_base), null)
    returning id into v_cand;

  insert into public.training_runs (kind, level, games_requested, baseline_brain_id, candidate_brain_id)
    values ('teach', 3, 1, v_base, v_cand) returning id into v_teach_run;
  insert into public.training_runs (kind, level, games_requested, baseline_brain_id)
    values ('train', 3, 1, v_base) returning id into v_train_run;

  insert into public.sim_games (training_run_id, host_deck, guest_deck, host_brain_id, guest_brain_id, winner, turns)
    values (v_teach_run, array['a','b','c','d','e'], array['f','g','h','i','j'], v_cand, v_base, 'host', 5)
    returning id into v_sim_game;

  insert into public.sim_unit_stats
    (training_run_id, sim_game_id, unit_id, card_slug, role, royal, side, won, turns_alive,
     damage_dealt, damage_taken, healing_done, kills, deaths, final_hp, carried)
  values
    (v_teach_run, v_sim_game, 'h1', 'zz-0115-teach-only', 'knight', false, 'host', true, 5,
     50, 10, 0, 1, 0, 40, false);

  select bool_or(card_slug = 'zz-0115-teach-only') into v_found
    from public.admin_card_performance(null);
  if v_found then
    raise exception '0115 self-test 1 FAILED: a teach-only card leaked into admin_card_performance(null)';
  end if;

  select bool_or(card_slug = 'zz-0115-teach-only') into v_found
    from public.admin_card_performance(v_teach_run);
  if not v_found then
    raise exception '0115 self-test 2 FAILED: admin_card_performance(explicit teach run id) should still show it';
  end if;

  -- cleanup
  delete from public.sim_unit_stats where training_run_id = v_teach_run;
  delete from public.sim_games where training_run_id = v_teach_run;
  delete from public.training_runs where id in (v_teach_run, v_train_run);
  delete from public.bot_brains where id = v_cand;

  raise notice '0115 self-test passed: teach-run games no longer pollute the all-time dashboards.';
end $$;
