-- 0125: pool 'preview'-kind runs into the "all-time" (p_run = null) mode of
-- the value dashboards -- admin_card_performance and admin_pair_synergy,
-- which admin_stat_value_model / admin_card_value / admin_ability_value /
-- admin_best_teams (0114/0116) all build on top of, so this one change
-- reaches every one of them.
--
-- Jared, on the just-shipped points system: "Why is the value of 1 attack
-- point increasing? Makes no sense all values are based on it." Root cause:
-- AdminTraining.tsx was passing THIS run's own id to every one of these
-- functions, so admin_stat_value_model refit its regression from scratch on
-- nothing but that one Simulate click's own ~40-100 games every time --
-- with only 13 active cards, a fit that small is genuinely noisy, so the
-- Attack-point coefficient (the anchor every other point value divides by)
-- visibly moved between clicks.
--
-- The fix in AdminTraining.tsx (same change as this migration) switches
-- those calls to p_run = null -- pooled across history instead of one
-- run's own noise. But p_run = null here has meant "every game from a
-- 'train'-kind run" since 0115, and NOTHING in this app has ever created a
-- 'train'-kind run (only admin_spot_check_team does, for an unrelated spot-
-- check feature) -- every game Jared has actually generated by clicking
-- "Simulate matches" is 'preview' kind. Switching to p_run = null with the
-- filter unchanged would have shown "insufficient data" instead of fixing
-- anything (verified: admin_stat_value_model(null) currently returns
-- exactly that, with n=0, before this migration).
--
-- 0115's caution about pooling 'teach' games doesn't actually apply to
-- 'preview': both create a fresh candidate brain and play it against the
-- live baseline, but a 'teach' run PROMOTES over the current live bot when
-- its candidate wins -- so pooling 'teach' games can retroactively make
-- history look like it was already superseded by a bot that didn't exist
-- yet when those games were played. 'preview' never touches the live bot
-- (admin_apply_training_run, the separate 'Train' button, is the only path
-- that promotes) -- it's just real 5v5 battles. And for what these
-- dashboards actually measure -- which CARDS won, not which BOT brain did
-- -- a game's outcome is exactly as real regardless of which brain played
-- either side; that's genuine noise that averages out over enough games,
-- not a bias in which cards look strong. So: 'train' or 'preview', still
-- never 'teach'.
create or replace function public.admin_card_performance(p_run uuid default null)
returns table (
  card_slug text, role text, royal boolean, games int, win_rate numeric,
  avg_turns_alive numeric, avg_damage_dealt numeric, avg_damage_taken numeric,
  avg_healing_done numeric, avg_kills numeric, carried_count int, carry_rate numeric
)
language sql
stable
as $$
  select s.card_slug, max(s.role), bool_or(s.royal),
    count(*)::int, avg(s.won::int)::numeric,
    avg(s.turns_alive)::numeric, avg(s.damage_dealt)::numeric, avg(s.damage_taken)::numeric,
    avg(s.healing_done)::numeric, avg(s.kills)::numeric,
    sum(s.carried::int)::int, avg(s.carried::int)::numeric
  from public.sim_unit_stats s
  join public.training_runs r on r.id = s.training_run_id
  where (p_run is not null and s.training_run_id = p_run)
     or (p_run is null and r.kind in ('train', 'preview'))
  group by s.card_slug
  order by 5 desc
$$;

create or replace function public.admin_pair_synergy(p_run uuid default null, p_min_games int default 15)
returns table (card_a text, card_b text, games int, win_rate numeric, lift numeric)
language sql
stable
as $$
  with pairs as (
    select s1.sim_game_id, s1.card_slug as card_a, s2.card_slug as card_b, s1.won
    from public.sim_unit_stats s1
    join public.sim_unit_stats s2
      on s1.sim_game_id = s2.sim_game_id and s1.side = s2.side and s1.card_slug < s2.card_slug
    join public.training_runs r on r.id = s1.training_run_id
    where ((p_run is not null and s1.training_run_id = p_run)
        or (p_run is null and r.kind in ('train', 'preview')))
      and s2.training_run_id = s1.training_run_id
  ),
  agg as (
    select card_a, card_b, count(*)::int as games, avg(won::int)::numeric as win_rate
    from pairs group by card_a, card_b
  ),
  solo as (
    select s.card_slug, avg(s.won::int)::numeric as win_rate
    from public.sim_unit_stats s
    join public.training_runs r on r.id = s.training_run_id
    where (p_run is not null and s.training_run_id = p_run)
       or (p_run is null and r.kind in ('train', 'preview'))
    group by s.card_slug
  )
  select a.card_a, a.card_b, a.games, a.win_rate,
    (a.win_rate - (sa.win_rate + sb.win_rate) / 2.0) as lift
  from agg a
  join solo sa on sa.card_slug = a.card_a
  join solo sb on sb.card_slug = a.card_b
  where a.games >= p_min_games
  order by lift desc
$$;

-- Self-test: a card that ONLY appears in a 'teach'-kind run's stats must
-- still NOT show up in admin_card_performance(null) (the one thing 0115
-- actually needed to guarantee stays true) -- and a card that only appears
-- in a 'preview'-kind run now MUST show up (that's the actual fix).
do $$
declare
  v_admin uuid; v_level int := 3; v_base_id uuid; v_cand_id uuid;
  v_teach_run uuid; v_preview_run uuid; v_teach_game uuid; v_preview_game uuid;
  v_teach_slug text := 'zz0125teach'; v_preview_slug text := 'zz0125preview';
  v_n int;
begin
  select id into v_admin from public.profiles where is_admin limit 1;
  perform set_config('request.jwt.claim.sub', v_admin::text, true);
  select id into v_base_id from public.bot_brains where level = v_level and is_live limit 1;
  select id into v_cand_id from public.bot_brains where level = v_level limit 1;

  insert into public.training_runs (kind, level, games_requested, games_completed, status, candidate_brain_id, baseline_brain_id)
    values ('teach', v_level, 1, 1, 'completed', v_cand_id, v_base_id) returning id into v_teach_run;
  insert into public.training_runs (kind, level, games_requested, games_completed, status, candidate_brain_id, baseline_brain_id)
    values ('preview', v_level, 1, 1, 'completed', v_cand_id, v_base_id) returning id into v_preview_run;

  -- match_id is nullable on sim_games -- no need to also insert a row into
  -- matches (which has its own unrelated NOT NULL columns) just to satisfy
  -- a foreign key this self-test doesn't otherwise care about.
  insert into public.sim_games (training_run_id, host_deck, guest_deck, host_brain_id, guest_brain_id, winner, turns, capped)
    values (v_teach_run, array[v_teach_slug], array[v_teach_slug], v_base_id, v_cand_id, 'host', 5, false)
    returning id into v_teach_game;
  insert into public.sim_unit_stats (training_run_id, sim_game_id, unit_id, card_slug, role, royal, side, won, turns_alive, damage_dealt, damage_taken, healing_done, kills, deaths, final_hp, carried)
    values (v_teach_run, v_teach_game, 'u1', v_teach_slug, 'knight', false, 'host', true, 5, 10, 0, 0, 1, 0, 10, false);

  insert into public.sim_games (training_run_id, host_deck, guest_deck, host_brain_id, guest_brain_id, winner, turns, capped)
    values (v_preview_run, array[v_preview_slug], array[v_preview_slug], v_base_id, v_cand_id, 'host', 5, false)
    returning id into v_preview_game;
  insert into public.sim_unit_stats (training_run_id, sim_game_id, unit_id, card_slug, role, royal, side, won, turns_alive, damage_dealt, damage_taken, healing_done, kills, deaths, final_hp, carried)
    values (v_preview_run, v_preview_game, 'u1', v_preview_slug, 'knight', false, 'host', true, 5, 10, 0, 0, 1, 0, 10, false);

  select count(*) into v_n from public.admin_card_performance(null) where card_slug = v_teach_slug;
  if v_n <> 0 then
    raise exception '0125 self-test FAILED: teach-only card leaked into admin_card_performance(null)';
  end if;

  select count(*) into v_n from public.admin_card_performance(null) where card_slug = v_preview_slug;
  if v_n <> 1 then
    raise exception '0125 self-test FAILED: preview-only card did NOT appear in admin_card_performance(null) (got %)', v_n;
  end if;

  raise notice '0125 self-test passed: preview pools in, teach still does not.';

  -- cleanup
  delete from public.sim_unit_stats where training_run_id in (v_teach_run, v_preview_run);
  delete from public.sim_games where training_run_id in (v_teach_run, v_preview_run);
  delete from public.training_runs where id in (v_teach_run, v_preview_run);
end $$;
